services:
  - type: web
    name: SeedLink-airecognition
    env: python
    pythonVersion: "3.12"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
