services:
  - type: web
    name: SeedLink-airecognition
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Docker handles build
    startCommand: ""  # Docker CMD is used
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      # Add other environment variables here
      # - key: OPENAI_API_KEY
      #   value: "your-key"
