services:
  - type: web
    name: seedlink
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
```

3. Add `gunicorn` to your `requirements.txt`:
```
gunicorn==21.2.0